### ISSUE TITLE
minDate value

### ISSUE THREAD

**Issue by Hizabr** [umalqura/umalqura#21]
هل صحيح قيمة حقل (أقل تاريخ `minDate`) في الكلاس `UmAlQuraStatic.ts` ؟
القيمة الحالية: `private static readonly minDate = new Date(1900, 3, 30)`
أليس المفترض: `private static readonly minDate = new Date(1900, 4, 30)`؟

**Comment by alaatm** [comment]
In JavaScript, the month field in the `Date` constructor is zero-based. So, `0` is January, `1` is February, ..., `11` is December.
Hence, `new Date(1900, 3, 30)` gives April 30th, 1900.

See [this](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/Date#monthindex) for more info.

**Comment by Hizabr** [comment]
ألا بلا صحيح 😂 كيف غابت عن بالي🤦🏻‍♂️
