### ISSUE TITLE
Is valid function for Hijri dates

### ISSUE THREAD

**Issue by zuhairkareem** [umalqura/umalqura#27]
Is there a validate function for Hijri dates - for eg. 30-01-1415 is invalid date, but the uq function returns a result

```
  const greg = uq(1415, 1, 30);
  console.log(greg);
```

![image](https://github.com/umalqura/umalqura/assets/4180013/e8ca0639-11d7-42e8-853b-73640e43f527)

Do we have to simply compare returned hijri date in the object with the date we gave for conversion?

**Comment by zuhairkareem** [comment]
Any idea why according to Intl object of the browser, 30-10-1402 is invalid but is valid according to this library & https://www.ummulqura.org.sa/yearcalender.aspx?y=1402&l=True?

![image](https://github.com/umalqura/umalqura/assets/4180013/b2525fa1-f8dd-4895-b523-26338a936967)

**Comment by alaatm** [comment]
The library accepts days from 1 to 30 for hijri dates even if there is no 30. If you convert it back and forth it will be 1st of the next month if it was invalid.

You can use `daysInMonth` to determine the last day. i.e.
```js
const uq = umalqura(1415, 1, 1);
console.log(uq.daysInMonth); // 29
```

Alternatively, you can use `monthArray` which returns a 2d array for weeks/days of the month. This is best used if you want to display a full month view.

Regarding 30-10-1402, not sure why Intl object reports it as invalid. This library follows umalqura calendar which says it is valid.

**Comment by zuhairkareem** [comment]
Thanks for the reply @alaatm & for this great library,  It is very accurate.

I am using the hijri (year, month,day) in the returned object from uq and compare with user input to validate. I think this should be fine?

````
isValid(year: number, month: number, day: number): boolean {
    if(year < 1318 || year > 1500) {
      return false;
    }
    const greg = uq(year, month, day);
    console.log(`Hijri Input - ${year}-${month}-${day}`);
    console.log(`Hijri From converted - ${greg.hy}-${greg.hm}-${greg.hd}`);
    // Check the hijri date in the converted object from ummula-qura library
    // If they are same as input it is valid otherwise invalid.
    return (greg.hy === year && greg.hm === month && greg.hd === day)
  }
  ````

I also found one issue with https://www.ummulqura.org.sa/ site, the Date conversion to Gregorian in date conversion section & the full calendar itself, is off by one day
(https://www.ummulqura.org.sa/Index.aspx)
![image](https://github.com/umalqura/umalqura/assets/4180013/e882119f-7c08-48c8-b8b7-abd4b813f4ad)

(https://www.ummulqura.org.sa/yearcalender.aspx?y=1402&l=True)
![image](https://github.com/umalqura/umalqura/assets/4180013/45c08af5-add4-4947-8876-c16b544ddc40)

I guess we will have to check with their team.

**Comment by alaatm** [comment]
Older dates for umalqura calendar can have descrepancies because back then it was based on moon sightnings, which could later be determined to have errors. Recently it was changed so that days of month are calculated and not based on moon sightnings. That's why older dates might have errors but that is not the case for newer and future dates.
